config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lmingari/releases:
      branch: master
      repo: https://github.com/lmingari/releases
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-carmine-audemer.sh
        container: qc.acc_skimpy-amethyst-abyssinian
  QC.Doc:
    repos:
      github.com/lmingari/releases find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-orchid-drever.sh
        container: qc.doc_silly-platinum-loon
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-corn-ibis.sh
        container: qc.doc_bumpy-heliotrope-gerbil
      github.com/lmingari/releases markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-silver-gar.sh
        container: qc.doc_pasty-alizarin-impala
  QC.Lic:
    repos:
      github.com/lmingari/releases licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-charcoal-nightingale.sh
        container: qc.lic_bluesy-coral-booby
  QC.Met:
    repos:
      github.com/lmingari/releases cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-wheat-raccoon.sh
        container: qc.met_scaly-gamboge-lobster
  QC.Sec:
    repos:
      github.com/lmingari/releases bandit:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-viridian-ragdoll.sh
        container: qc.sec_muzzy-orchid-quoll
  QC.Sty:
    repos:
      github.com/lmingari/releases flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-champagne-wallaby.sh
        container: qc.sty_chewy-azure-pig
  QC.Ver:
    repos:
      github.com/lmingari/releases get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-myrtle-raccoon.sh
        container: qc.ver_cranky-blue-walrus
timeout: 5400
