config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lmingari/releases:
      branch: master
      repo: https://github.com/lmingari/releases
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-heliotrope-sparrow.sh
        container: qc.acc_lumpy-dandelion-grasshopper
  QC.Doc:
    repos:
      github.com/lmingari/releases find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-cobalt-albatross.sh
        container: qc.doc_crabby-sapphire-pig
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-olive-whippet.sh
        container: qc.doc_slaphappy-red-raccoon
      github.com/lmingari/releases markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-aquamarine-magpie.sh
        container: qc.doc_lumpy-lavender-kiwi
  QC.Lic:
    repos:
      github.com/lmingari/releases licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cinnabar-grouse.sh
        container: qc.lic_flimsy-rose-frigatebird
  QC.Met:
    repos:
      github.com/lmingari/releases cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-zucchini-wolverine.sh
        container: qc.met_thirsty-sangria-guppy
  QC.Sec:
    repos:
      github.com/lmingari/releases bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-brown-koala.sh
        container: qc.sec_frumpy-firebrick-bulldog
  QC.Sty:
    repos:
      github.com/lmingari/releases flake8:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cobalt-oyster.sh
        container: qc.sty_scummy-alizarin-dolphin
  QC.Ver:
    repos:
      github.com/lmingari/releases get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-malachite-lion.sh
        container: qc.ver_wimpy-brown-burmese
timeout: 5400
