config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lmingari/releases:
      branch: master
      repo: https://github.com/lmingari/releases
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-brown-akbash.sh
        container: qc.acc_squirrely-indigo-scorpion
  QC.Doc:
    repos:
      github.com/lmingari/releases find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-cerulean-scorpion.sh
        container: qc.doc_lumpy-cerise-civet
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-fuchsia-vulture.sh
        container: qc.doc_lanky-mustard-fousek
      github.com/lmingari/releases markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-indigo-hornet.sh
        container: qc.doc_skimpy-peach-vole
  QC.Lic:
    repos:
      github.com/lmingari/releases licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-firebrick-rottweiler.sh
        container: qc.lic_pokey-wheat-corgi
  QC.Met:
    repos:
      github.com/lmingari/releases cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-magnolia-deer.sh
        container: qc.met_flaky-puce-sheep
  QC.Sec:
    repos:
      github.com/lmingari/releases bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-apricot-panda.sh
        container: qc.sec_hilly-ruby-oyster
  QC.Sty:
    repos:
      github.com/lmingari/releases flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-tan-whale.sh
        container: qc.sty_tasty-amethyst-albatross
  QC.Ver:
    repos:
      github.com/lmingari/releases get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-champagne-moose.sh
        container: qc.ver_baggy-lilac-molly
timeout: 5400
