config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/lmingari/releases:
      branch: master
      repo: https://github.com/lmingari/releases
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-violet-coati.sh
        container: qc.acc_pokey-aquamarine-birman
  QC.Doc:
    repos:
      github.com/lmingari/releases find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-amaranth-collie.sh
        container: qc.doc_silly-platinum-tuatara
      github.com/lmingari/releases git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-periwinkle-peccary.sh
        container: qc.doc_seedy-seashell-lizard
      github.com/lmingari/releases markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-ochre-angelfish.sh
        container: qc.doc_squeaky-olive-wolfhound
  QC.Lic:
    repos:
      github.com/lmingari/releases licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-mustard-bandicoot.sh
        container: qc.lic_wheezy-carmine-russel
  QC.Met:
    repos:
      github.com/lmingari/releases cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-pumpkin-cuscus.sh
        container: qc.met_skimpy-rust-cassowary
  QC.Sec:
    repos:
      github.com/lmingari/releases bandit:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-khaki-dodo.sh
        container: qc.sec_trippy-chartreuse-dingo
  QC.Sty:
    repos:
      github.com/lmingari/releases flake8:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-ivory-tuatara.sh
        container: qc.sty_droopy-celadon-centipede
  QC.Ver:
    repos:
      github.com/lmingari/releases get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-asparagus-indri.sh
        container: qc.ver_grumpy-gold-labradoodle
timeout: 5400
